### ISSUE TITLE
newbie help

### ISSUE THREAD

**Issue by hribeir0** [sdalu/kuiristo#1]
Not particularly an issue, but I'm rather newbie and would like some help installing this. Do you think is possible?

**Comment by sdalu** [comment]
You need a mysql database configured and running, next:

~~~sh
git clone --recursive http://github.com/sdalu/kuiristo.git
git clone http://github.com/sdalu/kuiristo-yumi.git

cd kuiristo
cp config.yaml.sample config.yaml
vi config.yaml
bundle init --path vendor
rake db:init
rake import\[yumi\]

rake web:start
~~~

**Comment by hribeir0** [comment]
Thanks. That's the only part I "master". I've installed ruby, bundler and rake. No sure if I missed something. 
After I edit config.yaml adding db data (the host is localhost, right?) I try to run "bundle init --path vendor" and get "Unknown switches '--path' "

I'm sorry but I don't understand ruby, nor how to get this to work, nor how to access it later.. Are you able to help me?

**Comment by sdalu** [comment]
Sorry, my mistake: `bundle install --path vendor`
For `localhost` I tend to prefer: `127.0.0.1`

**Comment by hribeir0** [comment]
When I try to follow those commands I always find some package or gem (whtaever that is) or command missing. There's always some dependencies or whatever. I'm beginning to think this is somewhat impossible to achieve for someone without proper knowledge. 
Whenever I succeed on one step I find I need to take 2 extra steps before the next one and so one.

I'm trying to get to work on a centos server - if that adds some information. What do you think? Is this something I should pursue or should I give up? Any suggestion? 
Thanks and Merry Christmas

**Comment by hribeir0** [comment]
Anyhow, I believe this is the error I get at this stage, once I run "bundle install --path vendor"

# Sinatra
gem 'sinatra'
```

### Gemfile.lock

```
<No /home/info/kuiristo/Gemfile.lock found>
```

**Comment by sdalu** [comment]
It should install painlessly, at least for the dependencies, as they are resolved and installed by the bundle command.

For some of the gem to build (nokogiri, mysql2, rmagic, ...k), you will need to have the corresponding packages (or developer packages) installed on your os (libmxml, mysql/mariadb, ImageMagick, ...)

Have you tried to remove the previous install ( `cd /home/info && rm -rf kuiristo kuiristo-yumi` ) and start from scratch?

**Comment by hribeir0** [comment]
yes I have. At this stage the problem resides on the ImageMagik instalation. Here's the output:
root@hribeiro-back:~/kuiristo# gem install rmagick -v '2.16.0'
Building native extensions.  This could take a while...
ERROR:  Error installing rmagick:
	ERROR: Failed to build gem native extension.

    current directory: /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rmagick-2.16.0/ext/RMagick
/root/.rbenv/versions/2.4.3/bin/ruby -r ./siteconf20171225-17462-5jxas1.rb extconf.rb
checking for gcc... yes
checking for Magick-config... no
checking for pkg-config... yes
checking for outdated ImageMagick version (<= 6.4.9)... no
checking for presence of MagickWand API (ImageMagick version >= 6.9.0)... no
checking for Ruby version >= 1.8.5... yes
checking for stdint.h... yes
checking for sys/types.h... yes
checking for wand/MagickWand.h... no

Can't install RMagick 2.16.0. Can't find MagickWand.h.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/root/.rbenv/versions/2.4.3/bin/$(RUBY_BASE_NAME)

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0-static/rmagick-2.16.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rmagick-2.16.0 for inspection.
Results logged to /root/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0-static/rmagick-2.16.0/gem_make.out

**Comment by sdalu** [comment]
You are missing the centos packages related to development (ie: *-devel): ImageMagick-devel ....

**Comment by hribeir0** [comment]
can you please provide me with a list of packages that I should Install? I've google a bit but still no luck...

**Comment by sdalu** [comment]
I added requirements information:
* ruby >= 2.4 (not tested on 2.3)
* libxml2
* ImageMagick
* mysql/mariadb
* pHash (optional)

For the way to add the required packages on your OS, you will need to refer to its documentation (I'm not using Ubuntu or Centos)

**Comment by hribeir0** [comment]
Thank you! Finally I was able to install every dependencies. I think I've run rake web:start. It's stays with the following message "Listening on /tmp/kuiristo.sock, CTRL+C to stop".
What do I need to do next? How do I access the app?
Thank you and sorry for these (probably newbie) doubts.

**Comment by sdalu** [comment]
You can use an apache proxy, to access the `/tmp/kuiristo.sock` socket
~~~apache
<Location />
        ProxyPass        unix:/tmp/kuiristo.sock|http://127.0.0.1/
        ProxyPassReverse unix:/tmp/kuiritsto.sock|http://127.0.0.1/
</Location>
~~~

Or apply the fix  31d0cdb (I just commited), to have the app honor the `config.yaml` and listen to host/port defined in it.

You could wish to retrieve the last version.
Note that I made some change to the db schema, and for now the best upgrade path is to drop the database and recreate it.

**Comment by sdalu** [comment]
If you don't already have a web server running, you could wish to use in the `config.yaml`
~~~yaml
:web:
  :host: 0.0.0.0
  :port: 80
~~~
And next fire you web browser to access you server

**Comment by hribeir0** [comment]
Sorry for the lack of news. I did indeed given up. The whole set up is something I'm not capable of. Nice idea though.
Thank you for all the help
